In [119]:
import pandas as pd
import numpy as np
from patsy import dmatrices
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [120]:
train = pd.read_csv("train.csv")
train = train.drop(["Id"], axis=1)
train = train._get_numeric_data()

In [147]:
features = "+".join(["Q('{column}')".format(column=column) for column in set(train.columns) - set(["SalePrice"])])
y, X = dmatrices("SalePrice ~ " + features, train, return_type='dataframe')

In [148]:
vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif["features"] = X.columns
vif.round(1).where(vif["VIF Factor"] >= 2).sort_values(by="VIF Factor", ascending = False)

/Users/markneedham/projects/kaggle/house-prices/a/lib/python3.6/site-packages/statsmodels/stats/outliers_influence.py:167: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)

      VIF Factor           features
20           inf  Q('LowQualFinSF')
10           inf    Q('BsmtFinSF2')
31           inf     Q('GrLivArea')
29           inf   Q('TotalBsmtSF')
2            inf     Q('BsmtUnfSF')
15           inf      Q('2ndFlrSF')
36           inf    Q('BsmtFinSF1')
6            inf      Q('1stFlrSF')
0   2.395680e+06          Intercept
5   6.100000e+00     Q('YearBuilt')
9   4.600000e+00   Q('GarageYrBlt')
8   4.600000e+00  Q('TotRmsAbvGrd')
30  4.400000e+00    Q('GarageArea')
33  4.300000e+00    Q('GarageCars')
17  3.400000e+00   Q('OverallQual')
24  3.100000e+00      Q('FullBath')
34  2.700000e+00  Q('YearRemodAdd')
16  2.300000e+00      Q('HalfBath')
21  2.300000e+00  Q('BedroomAbvGr')
22  2.200000e+00  Q('BsmtFullBath')
1            NaN                NaN
3            NaN                NaN
4            NaN                NaN
7            NaN                NaN
11           NaN                NaN
12           NaN                NaN
13           NaN                NaN
14           NaN                NaN
18           NaN                NaN
19           NaN                NaN
23           NaN                NaN
25           NaN                NaN
26           NaN                NaN
27           NaN                NaN
28           NaN                NaN
32           NaN                NaN
35           NaN                NaN

In [165]:
train.corr()["TotRmsAbvGrd"].sort_values(ascending = False)

TotRmsAbvGrd     1.000000
GrLivArea        0.825489
BedroomAbvGr     0.676620
2ndFlrSF         0.616423
FullBath         0.554784
SalePrice        0.533723
OverallQual      0.427452
1stFlrSF         0.409516
GarageCars       0.362289
LotFrontage      0.352096
HalfBath         0.343415
GarageArea       0.337822
Fireplaces       0.326114
TotalBsmtSF      0.285573
MasVnrArea       0.280682
KitchenAbvGr     0.256045
BsmtUnfSF        0.250647
OpenPorchSF      0.234192
YearRemodAdd     0.191740
LotArea          0.190015
WoodDeckSF       0.165984
GarageYrBlt      0.148112
LowQualFinSF     0.131185
YearBuilt        0.095589
PoolArea         0.083757
ScreenPorch      0.059383
BsmtFinSF1       0.044316
MSSubClass       0.040380
MoSold           0.036907
MiscVal          0.024763
EnclosedPorch    0.004151
3SsnPorch       -0.006683
BsmtHalfBath    -0.023836
YrSold          -0.034516
BsmtFinSF2      -0.035227
BsmtFullBath    -0.053275
OverallCond     -0.057583
Name: TotRmsAbvGrd, dtype: float64

In [166]:
def calculate_vif(data, columns):
    features = "+".join(["Q('{column}')".format(column=column) for column in columns])
    y, X = dmatrices("SalePrice ~ " + features, train, return_type='dataframe')

    vif = pd.DataFrame()
    vif["VIF Factor"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
    vif["features"] = X.columns
    return vif.round(1).where(vif["VIF Factor"] >= 2).sort_values(by="VIF Factor", ascending = False)
                                                  
calculate_vif(train, set(train.columns) - set(["SalePrice", "GarageYrBlt", "YearRemodAdd", "OverallQual", "GarageArea", "TotRmsAbvGrd"]))

/Users/markneedham/projects/kaggle/house-prices/a/lib/python3.6/site-packages/statsmodels/stats/outliers_influence.py:167: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)

      VIF Factor           features
2            inf     Q('BsmtUnfSF')
6            inf      Q('1stFlrSF')
8            inf    Q('BsmtFinSF2')
13           inf      Q('2ndFlrSF')
17           inf  Q('LowQualFinSF')
26           inf   Q('TotalBsmtSF')
27           inf     Q('GrLivArea')
31           inf    Q('BsmtFinSF1')
0   2.409848e+06          Intercept
5   3.200000e+00     Q('YearBuilt')
21  2.800000e+00      Q('FullBath')
14  2.200000e+00      Q('HalfBath')
19  2.200000e+00  Q('BsmtFullBath')
1            NaN                NaN
3            NaN                NaN
4            NaN                NaN
7            NaN                NaN
9            NaN                NaN
10           NaN                NaN
11           NaN                NaN
12           NaN                NaN
15           NaN                NaN
16           NaN                NaN
18           NaN                NaN
20           NaN                NaN
22           NaN                NaN
23           NaN                NaN
24           NaN                NaN
25           NaN                NaN
28           NaN                NaN
29           NaN                NaN
30           NaN                NaN